### ISSUE TITLE
Undo of all played macro commands at once

### ISSUE THREAD

**Issue by myss** [xps/VSTextMacros#20]
I have created a complex macro that includes text inserts, deletions, cut and paste. If I execute the macro and want to undo it, I have to press ctrl-Z multiple times. I think that it would be better if everything would be undone at once.

**Comment by ygoe** [comment]
There seems to be an object named something like `EnvDTE.UndoContext` that has `Open(actionLabel)` and `Close()` methods as well as an `IsOpen` property. But I can't figure out where to get that instance from.

It would likely go into the `MacroCommandFilter.Playback` method. Unfortunately I can't try out this extension because Visual Studio 2015 won't start it. (I'd expect it to run it in an experimental VS instance but this one doesn't work.)

**Comment by ygoe** [comment]
Just tried it without the safety net, and it worked. [MSDN](https://msdn.microsoft.com/en-us/library/envdte._dte.aspx) told me where to get the required parts.
